export const AUTH_ERROR_CODES = {
  INVALID_TOKEN: 'INVALID_RESET_TOKEN',
  SAME_PASSWORD: 'SAME_PASSWORD',
  EXPIRED_TOKEN: 'TOKEN_EXPIRED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
} as const

export type AuthErrorCode = typeof AUTH_ERROR_CODES[keyof typeof AUTH_ERROR_CODES]
